name: All workflows

on:
  pull_request:
  push:
    branches: [main]

jobs:
  code-check:
    runs-on: ubuntu-latest
    container: python:3.10.0
    steps:
      - uses: actions/checkout@v2
      - run: pip install pipenv
      - run: pipenv install --dev --system
      - run: black --check ml_template/
      - run: pylint ml_template
      - run: pytest
      - run: mypy .
